import { AccountType, ControlType, NormalBalance } from '@prisma/client';

const { ASSET, LIABILITY, EQUITY, REVENUE, EXPENSE } = AccountType;
const { DEBIT, CREDIT } = NormalBalance;

export interface DefaultAccountSeed {
  number: string;
  name: string;
  nameAr?: string;
  nameFr?: string;
  nameEn?: string;
  accountClass: number;
  type: AccountType;
  normalBalance: NormalBalance;
  /** Parent account's `number`, or null for a class-root account. Parents are
   *  always listed before their children so ids resolve in a single pass. */
  parentNumber: string | null;
  isControl?: boolean;
  controlType?: ControlType;
}

// The commonly-used subset of the official Plan Comptable Libanais (FR-104),
// seeded into every company at registration. Names carry both Arabic (nameAr)
// and English (nameEn); `name` mirrors the English label. Type/normalBalance
// are derived from the account class with control-account refinements and are
// meant to be a sensible, editable starting point. The full official chart
// (all remaining accounts) is imported on demand via POST /accounts/import-
// official — see official-chart.ts.
export const DEFAULT_CHART: DefaultAccountSeed[] = [
  {
    number: '1',
    name: 'Permanent capital accounts',
    nameAr: 'حسابات الرساميل الدائمة',
    nameEn: 'Permanent capital accounts',
    accountClass: 1,
    type: EQUITY,
    normalBalance: CREDIT,
    parentNumber: null,
  },
  {
    number: '10',
    name: 'Capital',
    nameAr: 'رأس المال',
    nameEn: 'Capital',
    accountClass: 1,
    type: EQUITY,
    normalBalance: CREDIT,
    parentNumber: '1',
  },
  {
    number: '101',
    name: 'Company share capital',
    nameAr: 'رأس مال الشركة',
    nameEn: 'Company share capital',
    accountClass: 1,
    type: EQUITY,
    normalBalance: CREDIT,
    parentNumber: '10',
  },
  {
    number: '1013',
    name: 'Subscribed capital, called and paid',
    nameAr: 'رأس المال المكتتب المستدعى والمدفوع',
    nameEn: 'Subscribed capital, called and paid',
    accountClass: 1,
    type: EQUITY,
    normalBalance: CREDIT,
    parentNumber: '101',
  },
  {
    number: '109',
    name: "Owner's personal account (drawings)",
    nameAr: 'الحساب الشخصي لصاحب المؤسسة',
    nameEn: "Owner's personal account (drawings)",
    accountClass: 1,
    type: EQUITY,
    normalBalance: CREDIT,
    parentNumber: '10',
  },
  {
    number: '11',
    name: 'Reserves',
    nameAr: 'الاحتياطات',
    nameEn: 'Reserves',
    accountClass: 1,
    type: EQUITY,
    normalBalance: CREDIT,
    parentNumber: '1',
  },
  {
    number: '111',
    name: 'Legal reserve',
    nameAr: 'احتياطي قانوني',
    nameEn: 'Legal reserve',
    accountClass: 1,
    type: EQUITY,
    normalBalance: CREDIT,
    parentNumber: '11',
  },
  {
    number: '12',
    name: 'Retained results carried forward',
    nameAr: 'نتائج سابقة مدورة',
    nameEn: 'Retained results carried forward',
    accountClass: 1,
    type: EQUITY,
    normalBalance: CREDIT,
    parentNumber: '1',
  },
  {
    number: '121',
    name: 'Retained earnings carried forward (credit)',
    nameAr: 'نتائج سابقة مدورة دائنة',
    nameEn: 'Retained earnings carried forward (credit)',
    accountClass: 1,
    type: EQUITY,
    normalBalance: CREDIT,
    parentNumber: '12',
  },
  {
    number: '125',
    name: 'Retained losses carried forward (debit)',
    nameAr: 'نتائج سابقة مدورة مدينة',
    nameEn: 'Retained losses carried forward (debit)',
    accountClass: 1,
    type: EQUITY,
    normalBalance: CREDIT,
    parentNumber: '12',
  },
  {
    number: '13',
    name: 'Net result for the period (profit or loss)',
    nameAr: 'النتيجة الصافية للدورة المالية (ربح أو خسارة)',
    nameEn: 'Net result for the period (profit or loss)',
    accountClass: 1,
    type: EQUITY,
    normalBalance: CREDIT,
    parentNumber: '1',
  },
  {
    number: '138',
    name: 'Period result - profit',
    nameAr: 'نتيجة الدورة - أرباح',
    nameEn: 'Period result - profit',
    accountClass: 1,
    type: EQUITY,
    normalBalance: CREDIT,
    parentNumber: '13',
  },
  {
    number: '139',
    name: 'Period result - loss',
    nameAr: 'نتيجة الدورة - خسائر',
    nameEn: 'Period result - loss',
    accountClass: 1,
    type: EQUITY,
    normalBalance: CREDIT,
    parentNumber: '13',
  },
  {
    number: '2',
    name: 'Fixed-asset accounts',
    nameAr: 'حسابات الأصول الثابتة',
    nameEn: 'Fixed-asset accounts',
    accountClass: 2,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: null,
  },
  {
    number: '21',
    name: 'Intangible fixed assets',
    nameAr: 'الأصول الثابتة غير المادية',
    nameEn: 'Intangible fixed assets',
    accountClass: 2,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '2',
  },
  {
    number: '211',
    name: 'Business goodwill (key money, goodwill, customer base...)',
    nameAr: 'المؤسسة التجارية (الخلو¬ الشهرة¬ الزبائن...)',
    nameEn: 'Business goodwill (key money, goodwill, customer base...)',
    accountClass: 2,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '21',
  },
  {
    number: '212',
    name: 'Formation expenses',
    nameAr: 'مصاريف التأسيس',
    nameEn: 'Formation expenses',
    accountClass: 2,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '21',
  },
  {
    number: '22',
    name: 'Tangible fixed assets',
    nameAr: 'الأصول الثابتة المادية',
    nameEn: 'Tangible fixed assets',
    accountClass: 2,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '2',
  },
  {
    number: '223',
    name: 'Buildings',
    nameAr: 'الأبنية',
    nameEn: 'Buildings',
    accountClass: 2,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '22',
  },
  {
    number: '2231',
    name: 'Buildings',
    nameAr: 'الأبنية',
    nameEn: 'Buildings',
    accountClass: 2,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '223',
  },
  {
    number: '224',
    name: 'Technical installations and industrial machinery',
    nameAr: 'التجهيزات الفنية¬ والآلات الصناعية',
    nameEn: 'Technical installations and industrial machinery',
    accountClass: 2,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '22',
  },
  {
    number: '225',
    name: 'Transport vehicles',
    nameAr: 'آليات النقل',
    nameEn: 'Transport vehicles',
    accountClass: 2,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '22',
  },
  {
    number: '226',
    name: 'Other tangible fixed assets',
    nameAr: 'اصول ثابتة مادية أخرى',
    nameEn: 'Other tangible fixed assets',
    accountClass: 2,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '22',
  },
  {
    number: '2262',
    name: 'Office and IT equipment',
    nameAr: 'أدوات مكتبية ومعلوماتية',
    nameEn: 'Office and IT equipment',
    accountClass: 2,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '226',
  },
  {
    number: '2263',
    name: 'Furniture',
    nameAr: 'أثاث',
    nameEn: 'Furniture',
    accountClass: 2,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '226',
  },
  {
    number: '28',
    name: 'Accumulated depreciation of fixed assets',
    nameAr: 'مجمع استهلاكات الأصول الثابتة',
    nameEn: 'Accumulated depreciation of fixed assets',
    accountClass: 2,
    type: ASSET,
    normalBalance: CREDIT,
    parentNumber: '2',
  },
  {
    number: '282',
    name: 'Depreciation of tangible fixed assets',
    nameAr: 'استهلاكات الأصول الثابتة المادية',
    nameEn: 'Depreciation of tangible fixed assets',
    accountClass: 2,
    type: ASSET,
    normalBalance: CREDIT,
    parentNumber: '28',
  },
  {
    number: '2823',
    name: 'Buildings',
    nameAr: 'الأبنية',
    nameEn: 'Buildings',
    accountClass: 2,
    type: ASSET,
    normalBalance: CREDIT,
    parentNumber: '282',
  },
  {
    number: '2825',
    name: 'Transport vehicles',
    nameAr: 'آليات النقل',
    nameEn: 'Transport vehicles',
    accountClass: 2,
    type: ASSET,
    normalBalance: CREDIT,
    parentNumber: '282',
  },
  {
    number: '3',
    name: 'Inventory and work in progress',
    nameAr: 'المخزون وقيد الصنع',
    nameEn: 'Inventory and work in progress',
    accountClass: 3,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: null,
  },
  {
    number: '31',
    name: 'Raw materials or supplies',
    nameAr: 'مواد أولية أو إستهلاكية',
    nameEn: 'Raw materials or supplies',
    accountClass: 3,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '3',
  },
  {
    number: '311',
    name: 'Raw materials',
    nameAr: 'مواد أولية',
    nameEn: 'Raw materials',
    accountClass: 3,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '31',
  },
  {
    number: '37',
    name: 'Merchandise (goods for resale)',
    nameAr: 'البضائع (المعدة للبيع)',
    nameEn: 'Merchandise (goods for resale)',
    accountClass: 3,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '3',
    // Inventory valuation control account (FR-402/FR-501). Vendor bills post
    // DR here; sub-ledger valuation is the stock ledger, so it's non-postable
    // directly (like AR/AP).
    isControl: true,
    controlType: ControlType.INVENTORY,
  },
  {
    number: '371',
    name: 'Merchandise - category 1',
    nameAr: '371',
    nameEn: 'Merchandise - category 1',
    accountClass: 3,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '37',
  },
  {
    number: '4',
    name: 'Receivable and payable accounts (third parties)',
    nameAr: 'حسابات الذمم',
    nameEn: 'Receivable and payable accounts (third parties)',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: null,
  },
  {
    number: '40',
    name: 'Suppliers',
    nameAr: 'الموردون',
    nameEn: 'Suppliers',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '4',
    isControl: true,
    controlType: ControlType.AP,
  },
  {
    number: '401',
    name: 'Payables (investment/trading suppliers)',
    nameAr: 'ذمم دائنة (موردو الإستثمار)',
    nameEn: 'Payables (investment/trading suppliers)',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '40',
  },
  {
    number: '4011',
    name: 'Trading suppliers payables',
    nameAr: 'ذمم موردو الاستثمار',
    nameEn: 'Trading suppliers payables',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '401',
  },
  {
    number: '41',
    name: 'Customers',
    nameAr: 'الزبائن',
    nameEn: 'Customers',
    accountClass: 4,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '4',
    isControl: true,
    controlType: ControlType.AR,
  },
  {
    number: '411',
    name: 'Customer invoices',
    nameAr: 'فواتير الزبائن',
    nameEn: 'Customer invoices',
    accountClass: 4,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '41',
  },
  {
    number: '4111',
    name: 'Ordinary customers',
    nameAr: 'زبائن عاديون',
    nameEn: 'Ordinary customers',
    accountClass: 4,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '411',
  },
  {
    number: '42',
    name: 'Personnel',
    nameAr: 'المستخدمون',
    nameEn: 'Personnel',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '4',
  },
  {
    number: '421',
    name: 'Amounts payable to personnel (credit account)',
    nameAr: 'مدفوعات متوجبة للمستخدمين (حساب دائن)',
    nameEn: 'Amounts payable to personnel (credit account)',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '42',
  },
  {
    number: '43',
    name: 'Social security institutions',
    nameAr: 'مؤسسات الضمان الإجتماعي',
    nameEn: 'Social security institutions',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '4',
  },
  {
    number: '431',
    name: 'Payables to social security institutions',
    nameAr: 'ذمم دائنة تجاه مؤسسات الضمان الإجتماعي',
    nameEn: 'Payables to social security institutions',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '43',
  },
  {
    number: '44',
    name: 'State and public institutions',
    nameAr: 'الدولة والمؤسسات العامة',
    nameEn: 'State and public institutions',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '4',
  },
  {
    number: '442',
    name: 'Value added tax (VAT)',
    nameAr: 'ضريبة القيمة المضافة',
    nameEn: 'Value added tax (VAT)',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '44',
  },
  {
    number: '4426',
    name: 'Recoverable (deductible) VAT',
    nameAr: 'الضريبة على القيمة المضافة - الاسترجاع',
    nameEn: 'Recoverable (deductible) VAT',
    accountClass: 4,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '442',
    isControl: true,
    controlType: ControlType.VAT_IN,
  },
  {
    number: '44261',
    name: 'Deductible VAT on purchases with right of deduction',
    nameAr: 'ضريبة على القيمة المضافة متوجبة الدفع على المشتريات مع حق الحسم',
    nameEn: 'Deductible VAT on purchases with right of deduction',
    accountClass: 4,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '4426',
  },
  {
    number: '4427',
    name: 'Collected (output) VAT',
    nameAr: 'الضريبة على القيمة المضافة - المحصلة',
    nameEn: 'Collected (output) VAT',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '442',
    isControl: true,
    controlType: ControlType.VAT_OUT,
  },
  {
    number: '44271',
    name: 'Output VAT collected on sales',
    nameAr: 'ضريبة على القيمة المضافة محصلة على المبيعات',
    nameEn: 'Output VAT collected on sales',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '4427',
  },
  {
    number: '445',
    name: 'State and public institutions / other payables',
    nameAr: 'الدولة والمؤسسات العامة /ذمم دائنة أخرى',
    nameEn: 'State and public institutions / other payables',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '44',
  },
  {
    number: '449',
    name: 'State and public institutions / receivables',
    nameAr: 'الدولة والمؤسسات العامة / ذمم مدينة',
    nameEn: 'State and public institutions / receivables',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '44',
  },
  {
    number: '45',
    name: 'Partners / associates',
    nameAr: 'الشركاء',
    nameEn: 'Partners / associates',
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '4',
  },
  {
    number: '451',
    name: "Partners' current accounts",
    nameAr: 'حسابات الشركاء الجارية',
    nameEn: "Partners' current accounts",
    accountClass: 4,
    type: LIABILITY,
    normalBalance: CREDIT,
    parentNumber: '45',
  },
  {
    number: '5',
    name: 'Financial accounts',
    nameAr: 'الحسابات المالية',
    nameEn: 'Financial accounts',
    accountClass: 5,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: null,
  },
  {
    number: '51',
    name: 'Financial institutions',
    nameAr: 'المؤسسات المالية',
    nameEn: 'Financial institutions',
    accountClass: 5,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '5',
  },
  {
    number: '512',
    name: 'Banks',
    nameAr: 'بنوك',
    nameEn: 'Banks',
    accountClass: 5,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '51',
    isControl: true,
    controlType: ControlType.BANK,
  },
  {
    number: '5121',
    name: 'Bank of Lebanon and Overseas (BLOM)',
    nameAr: 'بنك لبنان والمهجر',
    nameEn: 'Bank of Lebanon and Overseas (BLOM)',
    accountClass: 5,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '512',
  },
  {
    number: '53',
    name: 'Cash on hand',
    nameAr: 'الصندوق',
    nameEn: 'Cash on hand',
    accountClass: 5,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '5',
  },
  {
    number: '531',
    name: 'Cash box',
    nameAr: 'صندوق النقدي',
    nameEn: 'Cash box',
    accountClass: 5,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '53',
    isControl: true,
    controlType: ControlType.CASH,
  },
  {
    number: '532',
    name: 'Cheques-for-collection cash box',
    nameAr: 'صندوق الشكات للتحصيل',
    nameEn: 'Cheques-for-collection cash box',
    accountClass: 5,
    type: ASSET,
    normalBalance: DEBIT,
    parentNumber: '53',
  },
  {
    number: '6',
    name: 'Expense accounts',
    nameAr: 'حسابات الأعباء',
    nameEn: 'Expense accounts',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: null,
  },
  {
    number: '60',
    name: 'Purchases of merchandise and change in inventory',
    nameAr: 'مشتريات البضاعة وقيمة التغيير في المخزون',
    nameEn: 'Purchases of merchandise and change in inventory',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '6',
    // Default COGS control account (FR-6xx). Sales invoices DR here at moving-
    // average cost when relieving inventory. The company default in the layered
    // item → category → company resolver; items/categories may override.
    isControl: true,
    controlType: ControlType.COGS,
  },
  {
    number: '601',
    name: 'Purchases of merchandise',
    nameAr: 'مشتريات البضاعة',
    nameEn: 'Purchases of merchandise',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '60',
  },
  {
    number: '6011',
    name: 'Purchases of merchandise',
    nameAr: 'مشتريات البضاعة',
    nameEn: 'Purchases of merchandise',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '601',
  },
  {
    number: '6018',
    name: 'Additional costs on purchase of goods and packaging',
    nameAr: 'نفقات إضافية على شراء البضائع والعبوات',
    nameEn: 'Additional costs on purchase of goods and packaging',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '601',
  },
  {
    number: '60181',
    name: 'Transport',
    nameAr: 'نقليات',
    nameEn: 'Transport',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '6018',
  },
  {
    number: '60185',
    name: 'Customs duties',
    nameAr: 'رسوم جمركية',
    nameEn: 'Customs duties',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '6018',
  },
  {
    number: '6019',
    name: 'Discounts earned',
    nameAr: 'حسومات مكتسبة',
    nameEn: 'Discounts earned',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '601',
  },
  {
    number: '61',
    name: 'Raw materials and consumables used',
    nameAr: 'مواد أولية وإستهلاكية مستخدمة',
    nameEn: 'Raw materials and consumables used',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '6',
  },
  {
    number: '62',
    name: 'Other external charges',
    nameAr: 'أعباء خارجية أخرى',
    nameEn: 'Other external charges',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '6',
  },
  {
    number: '626',
    name: 'External services',
    nameAr: 'الخدمات الخارجية',
    nameEn: 'External services',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '62',
  },
  {
    number: '6263',
    name: 'Rents (building services)',
    nameAr: 'الإيجارات (خدمات الأبنية)',
    nameEn: 'Rents (building services)',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '626',
  },
  {
    number: '6269',
    name: 'Other external services',
    nameAr: 'خدمات خارجية أخرى',
    nameEn: 'Other external services',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '626',
  },
  {
    number: '62693',
    name: 'Advertising',
    nameAr: 'اعلان',
    nameEn: 'Advertising',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '6269',
  },
  {
    number: '62695',
    name: 'Electricity',
    nameAr: 'كهرباء',
    nameEn: 'Electricity',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '6269',
  },
  {
    number: '63',
    name: 'Personnel charges',
    nameAr: 'أعباء المستخدمين',
    nameEn: 'Personnel charges',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '6',
  },
  {
    number: '631',
    name: 'Personnel salaries and wages',
    nameAr: 'رواتب وأجور المستخدمين',
    nameEn: 'Personnel salaries and wages',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '63',
  },
  {
    number: '6311',
    name: 'Salaries',
    nameAr: 'الرواتب',
    nameEn: 'Salaries',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '631',
  },
  {
    number: '63111',
    name: 'Personnel salaries',
    nameAr: 'رواتب المستخدمين',
    nameEn: 'Personnel salaries',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '6311',
  },
  {
    number: '635',
    name: 'Social charges / social security and insurance',
    nameAr: 'أعباء إجتماعية /ضمان إجتماعي وتامين',
    nameEn: 'Social charges / social security and insurance',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '63',
  },
  {
    number: '6351',
    name: 'Charges on salaries and wages paid',
    nameAr: 'أعباء مترتبة على الرواتب والأجور المدفوعة',
    nameEn: 'Charges on salaries and wages paid',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '635',
  },
  {
    number: '64',
    name: 'Taxes, duties and similar payments',
    nameAr: 'ضرائب ورسوم ومدفوعات مماثلة',
    nameEn: 'Taxes, duties and similar payments',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '6',
  },
  {
    number: '642',
    name: 'Municipal taxes and duties',
    nameAr: 'ضرائب ورسوم للبلديات',
    nameEn: 'Municipal taxes and duties',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '64',
  },
  {
    number: '65',
    name: 'Depreciation and provision charges - operating',
    nameAr: 'مخصصات الإستهلاكات والمؤونات للإستثمار',
    nameEn: 'Depreciation and provision charges - operating',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '6',
  },
  {
    number: '651',
    name: 'Depreciation charges',
    nameAr: 'مخصصات الإستهلاكات',
    nameEn: 'Depreciation charges',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '65',
  },
  {
    number: '66',
    name: 'Other ordinary administrative charges',
    nameAr: 'أعباء إدارية عادية أخرى',
    nameEn: 'Other ordinary administrative charges',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '6',
  },
  {
    number: '67',
    name: 'Financial charges',
    nameAr: 'الأعباء المالية',
    nameEn: 'Financial charges',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '6',
  },
  {
    number: '673',
    name: 'Interest and similar charges',
    nameAr: 'فوائد وأعباء مشابهة',
    nameEn: 'Interest and similar charges',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '67',
  },
  {
    number: '6736',
    name: 'Bank interest and interest on financing operations',
    nameAr: 'فوائد مصرفية وفوائد على عمليات التمويل',
    nameEn: 'Bank interest and interest on financing operations',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '673',
  },
  {
    number: '675',
    name: 'Negative exchange differences',
    nameAr: 'فروقات صرف سلبية',
    nameEn: 'Negative exchange differences',
    accountClass: 6,
    type: EXPENSE,
    normalBalance: DEBIT,
    parentNumber: '67',
  },
  {
    number: '7',
    name: 'Revenue accounts',
    nameAr: 'حسابات الإيرادات',
    nameEn: 'Revenue accounts',
    accountClass: 7,
    type: REVENUE,
    normalBalance: CREDIT,
    parentNumber: null,
  },
  {
    number: '70',
    name: 'Sales of merchandise',
    nameAr: 'مبيعات البضاعة',
    nameEn: 'Sales of merchandise',
    accountClass: 7,
    type: REVENUE,
    normalBalance: CREDIT,
    parentNumber: '7',
    // Default revenue control account (FR-6xx). Sales invoices CR line net here.
    // The company default in the layered item → category → company resolver;
    // items/categories may override.
    isControl: true,
    controlType: ControlType.REVENUE,
  },
  {
    number: '701',
    name: 'Invoices',
    nameAr: 'فواتير',
    nameEn: 'Invoices',
    accountClass: 7,
    type: REVENUE,
    normalBalance: CREDIT,
    parentNumber: '70',
  },
  {
    number: '7011',
    name: 'Sales subject to VAT',
    nameAr: 'مبيعات خاضعة لضريبة القيمة المضافة',
    nameEn: 'Sales subject to VAT',
    accountClass: 7,
    type: REVENUE,
    normalBalance: CREDIT,
    parentNumber: '701',
  },
  {
    number: '7012',
    name: 'Sales not subject to VAT',
    nameAr: 'مبيعات غير خاضعة لضريبة القيمة المضافة',
    nameEn: 'Sales not subject to VAT',
    accountClass: 7,
    type: REVENUE,
    normalBalance: CREDIT,
    parentNumber: '701',
  },
  {
    number: '709',
    name: 'Discounts granted',
    nameAr: 'حسومات ممنوحة',
    nameEn: 'Discounts granted',
    accountClass: 7,
    type: REVENUE,
    normalBalance: CREDIT,
    parentNumber: '70',
  },
  {
    number: '71',
    name: 'Products sold',
    nameAr: 'المنتجات المباعة',
    nameEn: 'Products sold',
    accountClass: 7,
    type: REVENUE,
    normalBalance: CREDIT,
    parentNumber: '7',
  },
  {
    number: '713',
    name: 'Services',
    nameAr: 'خدمات',
    nameEn: 'Services',
    accountClass: 7,
    type: REVENUE,
    normalBalance: CREDIT,
    parentNumber: '71',
  },
  {
    number: '74',
    name: 'Operating subsidies',
    nameAr: 'إعانات للإستثمار',
    nameEn: 'Operating subsidies',
    accountClass: 7,
    type: REVENUE,
    normalBalance: CREDIT,
    parentNumber: '7',
  },
  {
    number: '75',
    name: 'Reversals of provisions - operating',
    nameAr: 'إستردادات من المؤونات - للإستثمار',
    nameEn: 'Reversals of provisions - operating',
    accountClass: 7,
    type: REVENUE,
    normalBalance: CREDIT,
    parentNumber: '7',
  },
  {
    number: '76',
    name: 'Other operating income',
    nameAr: 'إيرادات أخرى ناتجة عن الإستثمار',
    nameEn: 'Other operating income',
    accountClass: 7,
    type: REVENUE,
    normalBalance: CREDIT,
    parentNumber: '7',
  },
  {
    number: '77',
    name: 'Financial income',
    nameAr: 'الإيرادات المالية',
    nameEn: 'Financial income',
    accountClass: 7,
    type: REVENUE,
    normalBalance: CREDIT,
    parentNumber: '7',
  },
  {
    number: '775',
    name: 'Positive exchange differences',
    nameAr: 'فروقات صرف إيجابية',
    nameEn: 'Positive exchange differences',
    accountClass: 7,
    type: REVENUE,
    normalBalance: CREDIT,
    parentNumber: '77',
  },
  {
    number: '78',
    name: 'Non-operating income',
    nameAr: 'إيرادات خارج الإستثمار',
    nameEn: 'Non-operating income',
    accountClass: 7,
    type: REVENUE,
    normalBalance: CREDIT,
    parentNumber: '7',
  },
];
